# Generated by Django 4.1.3 on 2022-12-18 09:02

import datetime
from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_Information_Model',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_employer', models.CharField(blank=True, max_length=500, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=500, null=True)),
                ('date_letter', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('letter_number', models.CharField(blank=True, max_length=500, null=True)),
                ('recipiant', models.CharField(blank=True, max_length=500, null=True)),
                ('coordinator', models.CharField(blank=True, max_length=500, null=True)),
                ('description_letter', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('date_deposit', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('amount_deposit', models.IntegerField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('shp_file', models.FileField(blank=True, null=True, upload_to=panel.models.shp_upload_location)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to=panel.models.files_upload_location)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Submit_Information',
            },
        ),
    ]
